//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFinances.BusinessLayer.Remote.Services.Empregados {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/eFinances.ServiceLayer.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpresaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimeiroNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UltimoNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId {
            get {
                return this.EmpresaIdField;
            }
            set {
                if ((this.EmpresaIdField.Equals(value) != true)) {
                    this.EmpresaIdField = value;
                    this.RaisePropertyChanged("EmpresaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimeiroNome {
            get {
                return this.PrimeiroNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimeiroNomeField, value) != true)) {
                    this.PrimeiroNomeField = value;
                    this.RaisePropertyChanged("PrimeiroNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UltimoNome {
            get {
                return this.UltimoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.UltimoNomeField, value) != true)) {
                    this.UltimoNomeField = value;
                    this.RaisePropertyChanged("UltimoNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Remote.Services.Empregados.IEmpregadosService")]
    public interface IEmpregadosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpregadosService/GetEmpregados", ReplyAction="http://tempuri.org/IEmpregadosService/GetEmpregadosResponse")]
        System.Data.DataTable GetEmpregados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpregadosService/GetEmpregado", ReplyAction="http://tempuri.org/IEmpregadosService/GetEmpregadoResponse")]
        eFinances.BusinessLayer.Remote.Services.Empregados.Cliente GetEmpregado(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpregadosServiceChannel : eFinances.BusinessLayer.Remote.Services.Empregados.IEmpregadosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpregadosServiceClient : System.ServiceModel.ClientBase<eFinances.BusinessLayer.Remote.Services.Empregados.IEmpregadosService>, eFinances.BusinessLayer.Remote.Services.Empregados.IEmpregadosService {
        
        public EmpregadosServiceClient() {
        }
        
        public EmpregadosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpregadosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpregadosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpregadosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetEmpregados() {
            return base.Channel.GetEmpregados();
        }
        
        public eFinances.BusinessLayer.Remote.Services.Empregados.Cliente GetEmpregado(int Id) {
            return base.Channel.GetEmpregado(Id);
        }
    }
}
